sharding:
  jdbc:
    dataSource:
      names: master,slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/guo?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
        username: root
        password: root
        maxPoolSize: 20
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3307/guo?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT
        username: root
        password: root
        maxPoolSize: 20
    config:
      masterslave: # 配置读写分离
        load-balance-algorithm-type: round_robin # 从库选择策略 random:随机 round_robin:轮询
        name: db1s2
        master-data-source-name: master
        slave-data-source-names: slave
      props:
        sql: # 开启SQL显示以及操作的是主库还是从库
          show: true
spring:
  main:
    allow-bean-definition-overriding: true
server.port: 8085
mybatis.config-location: classpath:mybatis-config.xml